version: 0.2

phases:
  install:
    commands:
      - bundle install 

#  pre_build:
#    commands:
#
#      # Discover and run unit tests in the 'tests' directory. For more information, see <https://docs.python.org/3/library/unittest.html#test-discovery>
#      - python -m unittest discover tests
  
  build:
    commands:
      - jekyll build

artifacts:
  type: S3
  base-directory: '_site'
  location: 'race-records-jekyll'
  files: 
    - 'assets/**/*'
    - '**/*.html'
    - '**/*.xml'
